language: php

php:
  - 7.1

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

services:
  - docker

jobs:
  include:
    - stage: sca
      script:
        - echo "$DIVANTE_DOCKER_PASSWORD" | docker login -u "$DIVANTE_DOCKER_USERNAME" --password-stdin registry-1.divante.pl:5000
        - docker run --rm --volume `pwd`:/project registry-1.divante.pl:5000/devops/phpcs --colors --exclude=PSR2.Methods.MethodDeclaration,PSR2.Classes.PropertyDeclaration --extensions=php --standard=PSR2,Security --ignore=vendor/* -s .
        - docker run --rm --volume `pwd`:/project jolicode/phaudit phpmd ./ text codesize --exclude vendor
        - docker run --rm --volume `pwd`:/project registry-1.divante.pl:5000/devops/phpdoccheck --directory=./ --exclude=vendor
        - docker run --rm --volume `pwd`:/project jolicode/phaudit phploc .
    - stage: push-to-docker
      script:
        - docker build -t bliskapaczkapl/magento-2:$COMMIT -f dev/docker/Dockerfile .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push bliskapaczkapl/magento-2:$COMMIT
        - if [ "$TRAVIS_TAG" ]; then
          docker tag bliskapaczkapl/magento-2:$COMMIT bliskapaczkapl/magento-2:$TRAVIS_TAG;
          docker push bliskapaczkapl/magento-2:$TRAVIS_TAG;
          fi
    - stage: push-to-packagist
      script:
        - curl -XPOST -H'content-type:application/json' "https://packagist.org/api/update-package?username=Sendit S.A.&apiToken=$PACKAGIST_API_TOKEN" -d'{"repository":{"url":"https://packagist.org/packages/sendit/bliskapaczka-magento-2"}}'
      if: tag
