language: php

php:
  - 7.1
  - 7.2

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
  matrix:
    - MAGENTO_VERSION=2.2.5
    - MAGENTO_VERSION=2.3.0

matrix:
  exclude:
    - php: 7.1
      env: MAGENTO_VERSION=2.2.5
    - php: 7.2
      env: MAGENTO_VERSION=2.2.5
    - php: 7.2
      env: MAGENTO_VERSION=2.3.0

services:
  - docker

script:
  - echo "$DIVANTE_DOCKER_PASSWORD" | docker login -u "$DIVANTE_DOCKER_USERNAME" --password-stdin registry-1.divante.pl:5000
  - docker run --rm --volume `pwd`:/project registry-1.divante.pl:5000/devops/phpcs --colors --exclude=PSR2.Methods.MethodDeclaration,PSR2.Classes.PropertyDeclaration --extensions=php --standard=PSR2,Security --ignore=vendor/* -s .
  - docker run --rm --volume `pwd`:/project jolicode/phaudit phpmd ./ text codesize --exclude vendor
  - docker run --rm --volume `pwd`:/project registry-1.divante.pl:5000/devops/phpdoccheck --directory=./ --exclude=vendor
  - docker run --rm --volume `pwd`:/project jolicode/phaudit phploc .

jobs:
  include:
    - stage: push-to-packagist
      script:
        - curl -XPOST -H'content-type:application/json' "https://packagist.org/api/update-package?username=Sendit S.A.&apiToken=$PACKAGIST_API_TOKEN" -d'{"repository":{"url":"https://packagist.org/packages/sendit/bliskapaczka-magento-2"}}'
      if: tag
      php: 7.2
    - stage: push-to-docker
      script:
        - PHP_VERSION=$(php -v | grep "^PHP" | awk '{print $2}' | sed "s/-.*//" | grep -o "^[^\.]*\.\?[^\.]*")
        - docker build -t bliskapaczkapl/magento-2:${PHP_VERSION}_${MAGENTO_VERSION}_${COMMIT} -f dev/docker/magento-$MAGENTO_VERSION/Dockerfile-php7.1 --build-arg commit=$COMMIT .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push bliskapaczkapl/magento-2:${PHP_VERSION}_${MAGENTO_VERSION}_${COMMIT}
        - if [ "$TRAVIS_TAG" ]; then
          docker tag bliskapaczkapl/magento-2:${PHP_VERSION}_${MAGENTO_VERSION}_${COMMIT} bliskapaczkapl/magento-2:$TRAVIS_TAG;
          docker push bliskapaczkapl/magento-2:$TRAVIS_TAG;
          fi
      php: 7.1
      env: MAGENTO_VERSION=2.2.5
    - script:
        - PHP_VERSION=$(php -v | grep "^PHP" | awk '{print $2}' | sed "s/-.*//" | grep -o "^[^\.]*\.\?[^\.]*")
        - docker build -t bliskapaczkapl/magento-2:${PHP_VERSION}_${MAGENTO_VERSION}_${COMMIT} -f dev/docker/magento-$MAGENTO_VERSION/Dockerfile-php7.2 --build-arg commit=$COMMIT .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push bliskapaczkapl/magento-2:${PHP_VERSION}_${MAGENTO_VERSION}_${COMMIT}
        - if [ "$TRAVIS_TAG" ]; then
          docker tag bliskapaczkapl/magento-2:${PHP_VERSION}_${MAGENTO_VERSION}_${COMMIT} bliskapaczkapl/magento-2:$TRAVIS_TAG;
          docker push bliskapaczkapl/magento-2:$TRAVIS_TAG;
          fi
        - if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then
          docker tag bliskapaczkapl/magento-2:${PHP_VERSION}_${MAGENTO_VERSION}_${COMMIT} bliskapaczkapl/magento-2:latest;
          docker push bliskapaczkapl/magento-2:latest;
          fi
      php: 7.2
      env: MAGENTO_VERSION=2.3.0
