version: "3"
services:
  magento:
    image: bliskapaczkapl/magento-2
    depends_on:
      - db
    ports:
      - "8080:80"
    env_file:
      - ./dev/docker/mysql/env
    environment:
      DB_HOST: db
      DOMAIN: 127.0.0.1:8080
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    env_file:
     - ./dev/docker/mysql/env
