version: "3"
services:
  magento:
    build:
      context: ./
      dockerfile: dev/docker/magento-2.2.5/Dockerfile-php7.1.dev
    volumes:
      - "./:/var/www/magento/app/code/Sendit/Bliskapaczka"
    ports:
      - "9000:9000"