version: "3"
services:
  magento:
    build:
      context: ./
      dockerfile: dev/docker/Dockerfile.dev
    volumes:
      - "./:/var/www/magento/app/code/Sendit/Bliskapaczka"
    ports:
      - "9000:9000"