#!/bin/bash

function info {
    printf "\033[0;36m===> \033[0;33m${1}\033[0m\n"
}

info "Sleep 10s, waiting for mysql "
sleep 10

runuser -s /bin/sh -c "cd /var/www/magento && /usr/local/bin/composer config http-basic.repo.magento.com bc4c30862f0179e4fb6588d87b42fabc cb1289ea2905db7d27baffcd717c6ed8" www-data

if [ $(mysql -N -s -h $DB_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD -e "select count(*) from information_schema.tables where table_schema='$MYSQL_DATABASE' and table_name='core_config_data';") -eq 1 ]; then
    info "Upgrade Magento"
	runuser -s /bin/sh -c "php /var/www/magento/bin/magento setup:upgrade" www-data
else
	runuser -s /bin/sh -c "composer require bliskapaczkapl/bliskapaczka-api-client '^3.0'" www-data

	info "Install Magento"
	runuser -s /bin/sh -c "php /var/www/magento/bin/magento setup:install --base-url=http://$DOMAIN \
	--db-host=$DB_HOST --db-name=$MYSQL_DATABASE --db-user=$MYSQL_USER --db-password=$MYSQL_PASSWORD \
	--backend-frontname=admin --admin-firstname=Magento --admin-lastname=User \
	--admin-email=admin@magento.localhost --admin-user=admin --admin-password=password123 \
	--language=pl_PL --currency=PLN --timezone=America/New_York --use-rewrites=1" www-data

	runuser -s /bin/sh -c "php /var/www/magento/bin/magento module:enable \
	Magento_CustomerSampleData \
	Magento_MsrpSampleData \
	Magento_CatalogSampleData \
	Magento_DownloadableSampleData \
	Magento_OfflineShippingSampleData \
	Magento_BundleSampleData \
	Magento_ConfigurableSampleData \
	Magento_ThemeSampleData \
	Magento_ProductLinksSampleData \
	Magento_ReviewSampleData \
	Magento_CatalogRuleSampleData \
	Magento_SwatchesSampleData \
	Magento_GroupedProductSampleData \
	Magento_TaxSampleData \
	Magento_CmsSampleData \
	Magento_SalesRuleSampleData \
	Magento_SalesSampleData \
	Magento_WidgetSampleData \
	Magento_WishlistSampleData" www-data
fi

cron

nginx

php-fpm

# MAGENTO_PATH=/var/www/magento

# info "Configure Magento"
# sed -i -e "s/DB_HOST/$DB_HOST/g" $MAGENTO_PATH/app/etc/local.xml
# sed -i -e "s/DB_USER/$MYSQL_USER/g" $MAGENTO_PATH/app/etc/local.xml
# sed -i -e "s/DB_PASS/$MYSQL_PASSWORD/g" $MAGENTO_PATH/app/etc/local.xml
# sed -i -e "s/DB_NAME/$MYSQL_DATABASE/g" $MAGENTO_PATH/app/etc/local.xml

# if [ $(mysql -N -s -h $DB_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD -e "select count(*) from information_schema.tables where table_schema='$MYSQL_DATABASE' and table_name='core_config_data';") -eq 1 ]; then
#     info "Nothing to do"
# else
# 	info "Import Magento Sample Data"
#     mysql -h $DB_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE < $MAGENTO_PATH/magento_sample_data_for_1.9.2.4.sql
# 	mysql -h $DB_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE -e 'UPDATE `core_resource` SET version = "1.6.2.0.5", data_version = "1.6.2.0.5" WHERE code = "customer_setup";'
# 	mysql -h $DB_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE -e 'INSERT INTO `admin_user` (firstname, lastname, email, username, password, created, lognum, reload_acl_flag, is_active, rp_token_created_at) VALUES ("Admin", "Admin", "admin@example.com", "admin", "482c811da5d5b4bc6d497ffa98491e38", NOW(), 0, 0, 1, NOW());'
# 	mysql -h $DB_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE -e 'INSERT INTO `admin_role` (parent_id,tree_level,sort_order,role_type,user_id,role_name) VALUES (1,2,0,"U",(SELECT user_id FROM admin_user WHERE username = "admin"),"Admin");'

# 	mysql -h $DB_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE -e 'UPDATE `core_config_data` SET value = "pl_PL" WHERE path = "general/locale/code" AND scope = "default";'
# 	mysql -h $DB_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE -e 'UPDATE `core_config_data` SET value = "PL" WHERE path = "general/country/default" AND scope = "default";'
# 	mysql -h $DB_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE -e 'UPDATE `core_store` SET name = "Polski" WHERE code = "default";'
# fi

while true; do
echo "Everything fine"
sleep 3600
done
